with open('lib/l10n/l10n.dart') as f:
    content = f.read()

new_en_entries = '''
    // UI i18n keys (auto-generated English identifiers)
    'about_to_upload': 'About to upload',
    'actual_case': 'Actual Case',
    'add_config': 'Add Config',
    'add_new_config': 'Add New Config',
    'add_project': 'Add Project',
    'add_project_experience': 'Add your project experience for quick interview review',
    'ai_config_management': 'AI Config Management',
    'always_show_upload_confirmation': 'Always show confirmation dialog before uploading data to AI service',
    'answer_draft': 'Answer Draft',
    'answer_template': 'Answer Template',
    'bound_account_reset_desc': 'If you have bound an email or WeChat, you can reset your password via verification code. Otherwise, submit a ticket.',
    'briefly_describe_issue': 'Briefly describe your issue',
    'briefly_describe_route_goal': 'Briefly describe the learning goal of this route',
    'capability': 'Capability',
    'change_password': 'Change Password',
    'char_3to20': '3-20 characters',
    'choose_template_by_scenario': 'Choose a template based on interview scenario and question depth',
    'choose_template_guide': 'Selecting a suitable answer template helps you organize your response structure',
    'clear_failed': 'Clear Failed',
    'clear_local_data': 'Clear Local Data',
    'clear_today_review_first': 'Clear today review first to prevent expired content from being forgotten',
    'click_top_right_add_config': 'Click + at top right to add config',
    'closed_not_used_for_scoring': 'When disabled, it will not be used for text scoring',
    'combine_actual_experience': '3. Combine with actual experience',
    'complete': 'Complete',
    'confirm_before_upload': 'Confirm Before Upload',
    'confirm_clear': 'Confirm Clear',
    'confirm_clear_all_data': 'Are you sure you want to clear all local data? This action cannot be undone.',
    'confirm_delete_config': 'Are you sure you want to delete this config?',
    'confirm_new_password': 'Confirm New Password',
    'confirm_new_password_hint': 'Re-enter new password',
    'confirm_password': 'Confirm Password',
    'confirm_password_hint': 'Re-enter password',
    'confirm_upload': 'Confirm Upload',
    'connection_failed': 'Connection Failed',
    'connection_success': 'Connection Successful',
    'create_new_account': 'Create New Account',
    'current_password': 'Current Password',
    'data_cleared': 'Data Cleared',
    'data_content_prefix': 'Data Content: ',
    'data_copied_to_clipboard': 'Data copied to clipboard, you can paste and save it',
    'data_management': 'Data Management',
    'data_upload_confirmation': 'Data Upload Confirmation',
    'deep_dig_practice': 'Deep Dig Practice',
    'delete_all_local_practice_data': 'Delete all locally saved practice data',
    'delete_domain_info': 'Deleting a domain does not delete content, only removes it from current view',
    'describe_issue_detail': 'Please describe your issue or suggestion in detail...',
    'describe_situation_for_reset': 'Please describe your situation in detail, including the username used during registration...',
    'detailed_description': 'Detailed Description',
    'drag_to_sort_delete_domain': 'Drag to sort, click delete button to remove domain',
    'edit_config': 'Edit Config',
    'edit_route': 'Edit Route',
    'enable': 'Enable',
    'example_forgot_password_reset': 'E.g.: Forgot password needs reset',
    'example_java_backend': 'E.g.: Java backend development',
    'example_openai_deepseek': 'E.g.: OpenAI, DeepSeek',
    'export_all_as_json': 'Export all local data as JSON file',
    'export_failed': 'Export Failed',
    'export_local_data': 'Export Local Data',
    'feedback_guide': 'Have any questions or suggestions? Let us know here.',
    'follow_up_count': 'Follow-up Questions',
    'follow_up_training_complete': 'Follow-up Training Complete',
    'follow_up_training_complete_excl': 'Follow-up Training Complete!',
    'forgot_current_password': 'Forgot your current password?',
    'forgot_password_q': 'Forgot Password?',
    'forgot_password_ticket_desc': 'If you have forgotten your password and cannot reset it through other methods, submit a ticket for admin review.',
    'have_account_login': 'Already have an account? Login',
    'high': 'High',
    'hint': 'Hint',
    'image_attachment': 'Image Attachment',
    'image_understanding': 'Image Understanding',
    'interviewer_focus': 'Interviewer Focus',
    'job_description': 'Job Description',
    'learning_mode': 'Learning Mode',
    'login_account': 'Login Account',
    'low': 'Low',
    'main_question': 'Main Question',
    'medium': 'Medium',
    'min_6_chars': 'At least 6 characters',
    'model': 'Model',
    'model_capability_statement': 'Model Capability Statement',
    'model_name': 'Model Name',
    'modification_failed': 'Modification Failed',
    'must_include': 'Must Include',
    'name': 'Name',
    'new_password': 'New Password',
    'new_password_same_as_old': 'New password cannot be the same as old password',
    'no_account_register': 'No account? Register',
    'no_ai_config': 'No AI Config',
    'no_ai_will_save_locally': 'No AI configured, will save as local practice',
    'no_saved_projects': 'No saved projects yet',
    'no_trainable_knowledge_points': 'No trainable knowledge points',
    'no_weakness_found': 'No weakness knowledge points found',
    'optional_domains': 'Optional Domains',
    'password': 'Password',
    'password_changed_successfully': 'Password changed successfully',
    'password_min_6_chars': 'Password must be at least 6 characters',
    'passwords_do_not_match': 'Passwords do not match',
    'personalized_adjustment': '2. Personalized adjustment',
    'please_confirm_new_password': 'Please confirm your new password',
    'please_confirm_password_again': 'Please re-enter your password',
    'please_enter_current_password': 'Please enter your current password',
    'please_enter_detailed_description': 'Please enter a detailed description',
    'please_enter_new_password': 'Please enter your new password',
    'please_enter_password': 'Please enter your password',
    'please_enter_route_name': 'Please enter route name',
    'please_enter_subject': 'Please enter a subject',
    'please_enter_username': 'Please enter your username',
    'please_select_at_least_one_domain': 'Please select at least one domain',
    'practice_again_round': 'Practice Another Round',
    'practice_expression': '4. Practice expression',
    'practice_verbally': 'Practice answering these questions verbally and record your answers',
    'privacy_protection': 'Privacy Protection',
    'privacy_protection_commitment': 'Privacy Protection Commitment',
    'privacy_settings': 'Privacy Settings',
    'project_deep_dig_library': 'Project Deep Dig Library',
    'question_mark': '?',
    'questions_count': 'Questions',
    'recall_scoring': 'Recall Scoring',
    'recent_practice': 'Recent Practice',
    'reference_answer': 'Reference Answer',
    'register': 'Register',
    'register_account': 'Register Account',
    'remember_and_practice_fluent_expression': 'Not just memorize content, but practice fluent expression',
    'reset_password_ticket': 'Reset Password Ticket',
    'route_description_optional': 'Route Description (optional)',
    'route_name': 'Route Name',
    'save_answer_drafts_locally': 'Save answer drafts locally',
    'save_jd_locally': 'Save JD/job description locally',
    'save_locally': 'Save Locally',
    'save_project_dig_info_locally': 'Save project deep dig info locally',
    'save_route': 'Save Route',
    'save_uploaded_images_locally': 'Save uploaded images locally',
    'save_voice_recordings_locally': 'Save voice recordings locally',
    'score_low_to_high': 'Score Low \u2192 High',
    'select_domains_guide': 'Select domains (click to add, drag to sort)',
    'select_suitable_template': '1. Choose a suitable template',
    'set_as_default': 'Set as Default',
    'start_today_practice': 'Start Today\'s Practice',
    'start_training': 'Start Training',
    'status': 'Status',
    'subject': 'Subject',
    'submit_failed': 'Submit Failed',
    'submit_feedback': 'Submit Feedback',
    'submit_ticket': 'Submit Ticket',
    'suitable_for_deep_discussion': 'Suitable for deep discussion, senior positions',
    'suitable_for_phone_interview': 'Suitable for phone interviews, quick answers',
    'support_image': 'Supports Image Understanding',
    'support_raw_audio': 'Supports Raw Audio Understanding',
    'support_streaming': 'Supports Streaming Response',
    'support_text': 'Supports Text',
    'template_is_just_framework': 'The template is just a framework, fill in content based on the specific question',
    'template_usage_guide': 'Template Usage Guide',
    'testing': 'Testing...',
    'ticket_submitted': 'Ticket submitted, we will process it as soon as possible',
    'time_2to3min': '2-3 minutes',
    'time_30sec_to_1min': '30 seconds - 1 minute',
    'time_3to5min': '3-5 minutes',
    'total_weaknesses': 'Total Weaknesses',
    'training_suggestion': 'It is recommended to train 5-10 weak points daily for 1 week for significant improvement',
    'transcribe_before_scoring': 'When disabled, you can still transcribe to text before scoring',
    'update_content': 'Update Content',
    'updated_at': 'Updated at',
    'upload_confirmation': 'Upload Confirmation',
    'upload_images_max5': 'Upload Images (optional, max 5)',
    'usage_purpose': 'Usage Purpose',
    'usage_tag': 'Usage Tag',
    'use_real_cases': 'Support your answers with real cases from your projects',
    'use_this_template': 'Use This Template',
    'username_min_3_chars': 'Username must be at least 3 characters',
    'verification_code_reset': 'Verification Code Reset',
    'voice_recording': 'Voice Recording',
    // Existing _zh-only keys translated to English
    'answer_hint': 'Enter your recall answer here...',
    'template_standard_example': 'Q: What is HashMap?\n\nA: HashMap is a Map interface implementation in Java...',
    'cloud_sync_wont_block': 'Cloud sync failure will not block learning, local events will wait for retry.',
    'today_review': 'Today\'s Review',
    'today_review_complete': 'Today\'s Review Complete!',
    'today_review_queue': 'Today\'s Review Queue',
    'clear_today_review': 'Clear Today\'s Review',
    'disabled_domains_info': 'Disabled domains will not be shown on the home page, but content will not be deleted',
'''

en_brace_pos = content.rfind('  };\n\n  static String get(String key,')
new_content = content[:en_brace_pos] + new_en_entries + '\n' + content[en_brace_pos:]

with open('lib/l10n/l10n.dart', 'w') as f:
    f.write(new_content)

print('Done - added new keys to _en map')