// Mocks generated by Mockito 5.4.6 from annotations
// in mianshi_zhilian/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i11;
import 'dart:typed_data' as _i13;

import 'package:http/http.dart' as _i2;
import 'package:mianshi_zhilian/models/ai_config.dart' as _i14;
import 'package:mianshi_zhilian/models/app_settings.dart' as _i9;
import 'package:mianshi_zhilian/models/domain.dart' as _i5;
import 'package:mianshi_zhilian/models/topic.dart' as _i6;
import 'package:mianshi_zhilian/models/user_progress.dart' as _i8;
import 'package:mianshi_zhilian/services/ai_service.dart' as _i3;
import 'package:mianshi_zhilian/services/content_api_service.dart' as _i4;
import 'package:mianshi_zhilian/services/endpoint_fallback_client.dart' as _i15;
import 'package:mianshi_zhilian/services/route_resolver.dart' as _i16;
import 'package:mianshi_zhilian/services/storage_service.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiTestResult_2 extends _i1.SmartFake implements _i3.AiTestResult {
  _FakeAiTestResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContentApiService_3 extends _i1.SmartFake
    implements _i4.ContentApiService {
  _FakeContentApiService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDomain_4 extends _i1.SmartFake implements _i5.Domain {
  _FakeDomain_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopic_5 extends _i1.SmartFake implements _i6.Topic {
  _FakeTopic_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_6 extends _i1.SmartFake
    implements _i7.SharedPreferences {
  _FakeSharedPreferences_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePrepPlan_7 extends _i1.SmartFake implements _i8.PrepPlan {
  _FakePrepPlan_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalProfile_8 extends _i1.SmartFake implements _i8.LocalProfile {
  _FakeLocalProfile_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncSettings_9 extends _i1.SmartFake implements _i8.SyncSettings {
  _FakeSyncSettings_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSettings_10 extends _i1.SmartFake implements _i9.AppSettings {
  _FakeAppSettings_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i10.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i10.Future<_i2.Response>);

  @override
  _i10.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i10.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i10.Future<_i2.Response>);

  @override
  _i10.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i10.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Response>);

  @override
  _i10.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i10.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Response>);

  @override
  _i10.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i10.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Response>);

  @override
  _i10.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i10.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Response>);

  @override
  _i10.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<_i13.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i10.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
          )
          as _i10.Future<_i13.Uint8List>);

  @override
  _i10.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i10.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_1(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i10.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i3.AiService {
  MockAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<Map<String, dynamic>> evaluateAnswer({
    required _i14.AiConfig? config,
    required String? topicTitle,
    required List<String>? mustHave,
    required List<String>? goodToHave,
    required List<String>? commonMistakes,
    Map<String, int>? scoreWeights,
    required String? userAnswer,
    required String? language,
    _i13.Uint8List? imageBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#evaluateAnswer, [], {
              #config: config,
              #topicTitle: topicTitle,
              #mustHave: mustHave,
              #goodToHave: goodToHave,
              #commonMistakes: commonMistakes,
              #scoreWeights: scoreWeights,
              #userAnswer: userAnswer,
              #language: language,
              #imageBytes: imageBytes,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Stream<String> evaluateAnswerStream({
    required _i14.AiConfig? config,
    required String? topicTitle,
    required List<String>? mustHave,
    required List<String>? goodToHave,
    required List<String>? commonMistakes,
    Map<String, int>? scoreWeights,
    required String? userAnswer,
    required String? language,
    _i13.Uint8List? imageBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#evaluateAnswerStream, [], {
              #config: config,
              #topicTitle: topicTitle,
              #mustHave: mustHave,
              #goodToHave: goodToHave,
              #commonMistakes: commonMistakes,
              #scoreWeights: scoreWeights,
              #userAnswer: userAnswer,
              #language: language,
              #imageBytes: imageBytes,
            }),
            returnValue: _i10.Stream<String>.empty(),
          )
          as _i10.Stream<String>);

  @override
  _i10.Future<_i3.AiTestResult> testTextConnection(_i14.AiConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#testTextConnection, [config]),
            returnValue: _i10.Future<_i3.AiTestResult>.value(
              _FakeAiTestResult_2(
                this,
                Invocation.method(#testTextConnection, [config]),
              ),
            ),
          )
          as _i10.Future<_i3.AiTestResult>);

  @override
  _i10.Future<bool> testConnection(_i14.AiConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, [config]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  bool isConfigAvailable(_i14.AiConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#isConfigAvailable, [config]),
            returnValue: false,
          )
          as bool);

  @override
  _i10.Future<_i3.AiTestResult> testAudioConnection(_i14.AiConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#testAudioConnection, [config]),
            returnValue: _i10.Future<_i3.AiTestResult>.value(
              _FakeAiTestResult_2(
                this,
                Invocation.method(#testAudioConnection, [config]),
              ),
            ),
          )
          as _i10.Future<_i3.AiTestResult>);

  @override
  _i10.Future<String> transcribeAudio({
    required _i14.AiConfig? config,
    required _i13.Uint8List? audioBytes,
    String? language = 'zh',
    String? fileName = 'audio.wav',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transcribeAudio, [], {
              #config: config,
              #audioBytes: audioBytes,
              #language: language,
              #fileName: fileName,
            }),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#transcribeAudio, [], {
                  #config: config,
                  #audioBytes: audioBytes,
                  #language: language,
                  #fileName: fileName,
                }),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Stream<String> sendMessageStream({
    required _i14.AiConfig? config,
    required String? userMessage,
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageStream, [], {
              #config: config,
              #userMessage: userMessage,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i10.Stream<String>.empty(),
          )
          as _i10.Stream<String>);

  @override
  _i10.Future<String> sendMessage(
    String? prompt, {
    required _i14.AiConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [prompt], {#config: config}),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#sendMessage, [prompt], {#config: config}),
              ),
            ),
          )
          as _i10.Future<String>);
}

/// A class which mocks [ContentApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentApiService extends _i1.Mock implements _i4.ContentApiService {
  MockContentApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.ContentApiService switchBaseUrl(String? newBaseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#switchBaseUrl, [newBaseUrl]),
            returnValue: _FakeContentApiService_3(
              this,
              Invocation.method(#switchBaseUrl, [newBaseUrl]),
            ),
          )
          as _i4.ContentApiService);

  @override
  _i10.Future<Map<String, dynamic>> fetchManifest() =>
      (super.noSuchMethod(
            Invocation.method(#fetchManifest, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i5.Domain> fetchDomain(String? domainId, {String? entry}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDomain, [domainId], {#entry: entry}),
            returnValue: _i10.Future<_i5.Domain>.value(
              _FakeDomain_4(
                this,
                Invocation.method(#fetchDomain, [domainId], {#entry: entry}),
              ),
            ),
          )
          as _i10.Future<_i5.Domain>);

  @override
  _i10.Future<_i6.Topic> fetchTopic(String? topicPath) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopic, [topicPath]),
            returnValue: _i10.Future<_i6.Topic>.value(
              _FakeTopic_5(this, Invocation.method(#fetchTopic, [topicPath])),
            ),
          )
          as _i10.Future<_i6.Topic>);

  @override
  _i10.Future<List<_i6.Topic>> fetchDomainTopics(_i5.Domain? domain) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDomainTopics, [domain]),
            returnValue: _i10.Future<List<_i6.Topic>>.value(<_i6.Topic>[]),
          )
          as _i10.Future<List<_i6.Topic>>);
}

/// A class which mocks [EndpointFallbackClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockEndpointFallbackClient extends _i1.Mock
    implements _i15.EndpointFallbackClient {
  MockEndpointFallbackClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Response> request(
    _i16.EndpointService? service,
    String? method,
    String? path, {
    Map<String, String>? headers,
    Object? body,
    Duration? timeout = const Duration(seconds: 5),
    bool? fallbackOnAllHttpErrors = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [service, method, path],
              {
                #headers: headers,
                #body: body,
                #timeout: timeout,
                #fallbackOnAllHttpErrors: fallbackOnAllHttpErrors,
              },
            ),
            returnValue: _i10.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #request,
                  [service, method, path],
                  {
                    #headers: headers,
                    #body: body,
                    #timeout: timeout,
                    #fallbackOnAllHttpErrors: fallbackOnAllHttpErrors,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Response>);

  @override
  List<String> resolveUrls(
    _i16.EndpointService? service,
    String? path, {
    _i16.EndpointMode? mode = _i16.EndpointMode.auto,
    _i16.EndpointLane? activeLane,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resolveUrls,
              [service, path],
              {#mode: mode, #activeLane: activeLane},
            ),
            returnValue: <String>[],
          )
          as List<String>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i17.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i7.SharedPreferences> getInstance() =>
      (super.noSuchMethod(
            Invocation.method(#getInstance, []),
            returnValue: _i10.Future<_i7.SharedPreferences>.value(
              _FakeSharedPreferences_6(
                this,
                Invocation.method(#getInstance, []),
              ),
            ),
          )
          as _i10.Future<_i7.SharedPreferences>);

  @override
  _i10.Future<void> save(String? key, dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#save, [key, data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<dynamic> load(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#load, [key]),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<void> saveAiConfigs(List<_i14.AiConfig>? configs) =>
      (super.noSuchMethod(
            Invocation.method(#saveAiConfigs, [configs]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i14.AiConfig>> loadAiConfigs() =>
      (super.noSuchMethod(
            Invocation.method(#loadAiConfigs, []),
            returnValue: _i10.Future<List<_i14.AiConfig>>.value(
              <_i14.AiConfig>[],
            ),
          )
          as _i10.Future<List<_i14.AiConfig>>);

  @override
  _i10.Future<void> saveProgressMap(Map<String, _i8.TopicProgress>? map) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgressMap, [map]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, _i8.TopicProgress>> loadProgressMap() =>
      (super.noSuchMethod(
            Invocation.method(#loadProgressMap, []),
            returnValue: _i10.Future<Map<String, _i8.TopicProgress>>.value(
              <String, _i8.TopicProgress>{},
            ),
          )
          as _i10.Future<Map<String, _i8.TopicProgress>>);

  @override
  _i10.Future<void> saveSessions(List<_i8.PracticeSession>? sessions) =>
      (super.noSuchMethod(
            Invocation.method(#saveSessions, [sessions]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i8.PracticeSession>> loadSessions() =>
      (super.noSuchMethod(
            Invocation.method(#loadSessions, []),
            returnValue: _i10.Future<List<_i8.PracticeSession>>.value(
              <_i8.PracticeSession>[],
            ),
          )
          as _i10.Future<List<_i8.PracticeSession>>);

  @override
  _i10.Future<void> savePracticeAttempts(List<_i8.PracticeAttempt>? attempts) =>
      (super.noSuchMethod(
            Invocation.method(#savePracticeAttempts, [attempts]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i8.PracticeAttempt>> loadPracticeAttempts() =>
      (super.noSuchMethod(
            Invocation.method(#loadPracticeAttempts, []),
            returnValue: _i10.Future<List<_i8.PracticeAttempt>>.value(
              <_i8.PracticeAttempt>[],
            ),
          )
          as _i10.Future<List<_i8.PracticeAttempt>>);

  @override
  _i10.Future<void> saveMockInterviewSessions(
    List<_i8.MockInterviewSession>? sessions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveMockInterviewSessions, [sessions]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i8.MockInterviewSession>> loadMockInterviewSessions() =>
      (super.noSuchMethod(
            Invocation.method(#loadMockInterviewSessions, []),
            returnValue: _i10.Future<List<_i8.MockInterviewSession>>.value(
              <_i8.MockInterviewSession>[],
            ),
          )
          as _i10.Future<List<_i8.MockInterviewSession>>);

  @override
  _i10.Future<void> savePrepPlan(_i8.PrepPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#savePrepPlan, [plan]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i8.PrepPlan> loadPrepPlan() =>
      (super.noSuchMethod(
            Invocation.method(#loadPrepPlan, []),
            returnValue: _i10.Future<_i8.PrepPlan>.value(
              _FakePrepPlan_7(this, Invocation.method(#loadPrepPlan, [])),
            ),
          )
          as _i10.Future<_i8.PrepPlan>);

  @override
  _i10.Future<void> saveLocalProfile(_i8.LocalProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalProfile, [profile]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i8.LocalProfile> loadLocalProfile() =>
      (super.noSuchMethod(
            Invocation.method(#loadLocalProfile, []),
            returnValue: _i10.Future<_i8.LocalProfile>.value(
              _FakeLocalProfile_8(
                this,
                Invocation.method(#loadLocalProfile, []),
              ),
            ),
          )
          as _i10.Future<_i8.LocalProfile>);

  @override
  _i10.Future<void> saveSyncSettings(_i8.SyncSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSyncSettings, [settings]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i8.SyncSettings> loadSyncSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSyncSettings, []),
            returnValue: _i10.Future<_i8.SyncSettings>.value(
              _FakeSyncSettings_9(
                this,
                Invocation.method(#loadSyncSettings, []),
              ),
            ),
          )
          as _i10.Future<_i8.SyncSettings>);

  @override
  _i10.Future<void> saveSettings(_i9.AppSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i9.AppSettings> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i10.Future<_i9.AppSettings>.value(
              _FakeAppSettings_10(this, Invocation.method(#loadSettings, [])),
            ),
          )
          as _i10.Future<_i9.AppSettings>);

  @override
  _i10.Future<Map<String, dynamic>> exportAllData() =>
      (super.noSuchMethod(
            Invocation.method(#exportAllData, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> clearCacheData() =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheData, []),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<void> clearPracticeData() =>
      (super.noSuchMethod(
            Invocation.method(#clearPracticeData, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> saveJsonList(
    String? key,
    List<Map<String, dynamic>>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveJsonList, [key, data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<Map<String, dynamic>>> loadJsonList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#loadJsonList, [key]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> saveJsonObject(String? key, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveJsonObject, [key, data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> loadJsonObject(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#loadJsonObject, [key]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> saveDisabledDomains(List<String>? domainIds) =>
      (super.noSuchMethod(
            Invocation.method(#saveDisabledDomains, [domainIds]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<String>> loadDisabledDomains() =>
      (super.noSuchMethod(
            Invocation.method(#loadDisabledDomains, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> saveCustomRoutes(List<Map<String, dynamic>>? routes) =>
      (super.noSuchMethod(
            Invocation.method(#saveCustomRoutes, [routes]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<Map<String, dynamic>>> loadCustomRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#loadCustomRoutes, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>> exportSyncPackage(
    _i8.SyncSettings? syncSettings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportSyncPackage, [syncSettings]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  Map<String, dynamic> sanitizeSyncPackage(
    Map<String, dynamic>? package,
    _i8.SyncSettings? syncSettings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sanitizeSyncPackage, [package, syncSettings]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i10.Future<void> importSyncPackage(
    Map<String, dynamic>? package, {
    _i8.SyncSettings? syncSettings,
    bool? preserveLocalSensitiveData = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importSyncPackage,
              [package],
              {
                #syncSettings: syncSettings,
                #preserveLocalSensitiveData: preserveLocalSensitiveData,
              },
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> importAllData(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#importAllData, [data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setLastSyncTime(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSyncTime, [time]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<DateTime?> getLastSyncTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTime, []),
            returnValue: _i10.Future<DateTime?>.value(),
          )
          as _i10.Future<DateTime?>);

  @override
  _i10.Future<void> markSyncDirty() =>
      (super.noSuchMethod(
            Invocation.method(#markSyncDirty, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> hasSyncDirty() =>
      (super.noSuchMethod(
            Invocation.method(#hasSyncDirty, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> clearSyncDirty() =>
      (super.noSuchMethod(
            Invocation.method(#clearSyncDirty, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> getOrCreateDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateDeviceId, []),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateDeviceId, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> recordAnalyticsFeature(String? feature) =>
      (super.noSuchMethod(
            Invocation.method(#recordAnalyticsFeature, [feature]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> incrementAnalyticsCounter(String? key, {int? by = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#incrementAnalyticsCounter, [key], {#by: by}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> incrementAnalyticsNestedCounter(
    String? key,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#incrementAnalyticsNestedCounter, [key, name]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> snapshotAnalyticsBufferForFlush() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotAnalyticsBufferForFlush, []),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> markAnalyticsFlushSuccess(
    String? batchId,
    Map<String, dynamic>? sentDays,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAnalyticsFlushSuccess, [batchId, sentDays]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>> loadAnalyticsBuffer() =>
      (super.noSuchMethod(
            Invocation.method(#loadAnalyticsBuffer, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);
}
