name = "mianshi-zhilian-api"
main = "src/index.ts"
compatibility_date = "2026-05-27"

[[d1_databases]]
binding = "DB"
database_name = "mianshi-zhilian-db"
database_id = "3a10ced4-0cfd-41e0-aafd-480652eb4c47"

[vars]
CONTENT_MANIFEST_URL = "https://mianshi-zhilian-content.pages.dev/manifest.json"
TEST_CONTENT_BASE_URL = "https://mianshi-zhilian-content.pages.dev"
PROD_CONTENT_BASE_URL = "https://mianshi-zhilian-content.pages.dev"
JWT_SECRET = "mianshi-zhilian-jwt-secret-2026"
